Transform: AWS::Serverless-2016-10-31
Resources:
  captureFeed:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub Stack ${AWS::StackName} Function captureFeed
      CodeUri: captureFeed/
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          SALESBUNDLES_BUCKET_NAME: !Ref SalesBundles
          SALESBUNDLES_BUCKET_ARN: !GetAtt SalesBundles.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:GetObjectLegalHold
                - s3:GetObjectRetention
                - s3:GetObjectTorrent
                - s3:GetObjectVersion
                - s3:GetObjectVersionAcl
                - s3:GetObjectVersionForReplication
                - s3:GetObjectVersionTorrent
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:PutObject
                - s3:PutObjectLegalHold
                - s3:PutObjectRetention
                - s3:RestoreObject
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${SalesBundles}
                - !Sub arn:${AWS::Partition}:s3:::${SalesBundles}/*
      Architectures:
        - arm64
      ReservedConcurrentExecutions: 1
    Metadata:
      BuildMethod: makefile
  captureFeedLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${captureFeed}
  SalesBundles:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-salesbund-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SalesBundlesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SalesBundles
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Principal: '*'
            Action: '*'
            Effect: Deny
            Resource:
              - !GetAtt SalesBundles.Arn
              - !Sub ${SalesBundles.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'